//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public account()
        {
            this.auctions = new HashSet<auction>();
            this.auction_amount = new HashSet<auction_amount>();
            this.feedbacks = new HashSet<feedback>();
            this.orders = new HashSet<order>();
            this.transactions = new HashSet<transaction>();
        }
    
        public string username { get; set; }
        public string password { get; set; }
        public string role { get; set; }
        public int verify_email { get; set; }
        public bool status { get; set; }
    
        public virtual ICollection<auction> auctions { get; set; }
        public virtual ICollection<auction_amount> auction_amount { get; set; }
        public virtual ICollection<feedback> feedbacks { get; set; }
        public virtual ICollection<order> orders { get; set; }
        public virtual ICollection<transaction> transactions { get; set; }
    }
}
