//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArtGalleryDBEntities : DbContext
    {
        public ArtGalleryDBEntities()
            : base("name=ArtGalleryDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<account> accounts { get; set; }
        public DbSet<auction> auctions { get; set; }
        public DbSet<auction_amount> auction_amount { get; set; }
        public DbSet<cart> carts { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<commission> commissions { get; set; }
        public DbSet<feedback> feedbacks { get; set; }
        public DbSet<order> orders { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<product_cart> product_cart { get; set; }
        public DbSet<product_category> product_category { get; set; }
        public DbSet<profile> profiles { get; set; }
        public DbSet<transaction> transactions { get; set; }
    }
}
