//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class auction_amount
    {
        public int auction_amount_id { get; set; }
        public decimal price { get; set; }
        public string user_account { get; set; }
        public int auction_id { get; set; }
    
        public virtual account account { get; set; }
        public virtual auction auction { get; set; }
    }
}
