//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class auction
    {
        public auction()
        {
            this.auction_amount = new HashSet<auction_amount>();
        }
    
        public int auction_id { get; set; }
        public System.DateTime start_datetime { get; set; }
        public System.DateTime end_datetime { get; set; }
        public int product_id { get; set; }
        public string admin_account { get; set; }
    
        public virtual account account { get; set; }
        public virtual product product { get; set; }
        public virtual ICollection<auction_amount> auction_amount { get; set; }
    }
}
