//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public cart()
        {
            this.commissions = new HashSet<commission>();
            this.product_cart = new HashSet<product_cart>();
        }
    
        public int cart_id { get; set; }
        public decimal cart_price { get; set; }
    
        public virtual ICollection<commission> commissions { get; set; }
        public virtual ICollection<product_cart> product_cart { get; set; }
    }
}
