//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.product_category = new HashSet<product_category>();
        }
    
        public int category_id { get; set; }
        public string category_name { get; set; }
        public string content { get; set; }
    
        public virtual ICollection<product_category> product_category { get; set; }
    }
}
