//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.commissions = new HashSet<commission>();
        }
    
        public int order_id { get; set; }
        public string user_account { get; set; }
        public System.DateTime order_datetime { get; set; }
        public bool status { get; set; }
        public int product_id { get; set; }
    
        public virtual account account { get; set; }
        public virtual ICollection<commission> commissions { get; set; }
        public virtual product product { get; set; }
    }
}
