//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.auctions = new HashSet<auction>();
            this.orders = new HashSet<order>();
            this.product_cart = new HashSet<product_cart>();
            this.product_category = new HashSet<product_category>();
        }
    
        public int product_id { get; set; }
        public string product_title { get; set; }
        public string content { get; set; }
        public decimal product_price { get; set; }
        public string images { get; set; }
        public string thumbnail { get; set; }
        public string path { get; set; }
        public bool isShow { get; set; }
    
        public virtual ICollection<auction> auctions { get; set; }
        public virtual ICollection<order> orders { get; set; }
        public virtual ICollection<product_cart> product_cart { get; set; }
        public virtual ICollection<product_category> product_category { get; set; }
    }
}
