//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_category
    {
        public int product_category_id { get; set; }
        public int category_id { get; set; }
        public int product_id { get; set; }
    
        public virtual category category { get; set; }
        public virtual product product { get; set; }
    }
}
