//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class profile
    {
        public string username { get; set; }
        public string fullname { get; set; }
        public string email { get; set; }
        public int phone { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string address { get; set; }
        public string hobby { get; set; }
        public string avatar { get; set; }
    }
}
